//  ***************************************************************************
//  COPYRIGHT 2013 TO THE PRESENT   RHEINMETALL AIR DEFENCE AG   CH-8050 ZURICH
//
//  SOFTWARE DEVELOPMENT DEPARTMENT
//  ***************************************************************************
/*!
//  \file    ModPrefix.hpp
//
//  \author  Yves Strube (file template author)
//
//  \brief   Defines the module prefix
*/
//  ***************************************************************************

#ifndef REP_MODPREFIX_HPP_INCLUDED
#define REP_MODPREFIX_HPP_INCLUDED

/*
 * DO NOT EDIT: This file is automatically generated.
 * The module prefix uniquely (with respect to RAD) identifies one module.
 */

#define MOD__REPORTING_TOOL "REP" // ReportingTool

// MD5 digest = 9bcff0837e034e946f5ea1c494ba4639
#endif // REP_MODPREFIX_HPP_INCLUDED
